- name: Deploy monitoring stack on localhost
  hosts: localhost
  connection: local
  tasks:
    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus
        ports:
          - "9090:9090"
        volumes:
          - "/home/user/weather-app/configs/prometheus.yaml:/etc/prometheus/prometheus.yml"
        state: started
        restart_policy: always

    - name: Run Blackbox Exporter container
      docker_container:
        name: blackbox-exporter
        image: prom/blackbox-exporter
        ports:
          - "9115:9115"
        state: started
        restart_policy: always

    - name: start Grafana
      docker_container:
        name: grafana
        image: grafana/grafana
        ports:
          - "3000:3000"
        state: started
        restart_policy: always